version: "3.3"
services:
  concierge:
    build: .
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl http://127.0.0.1:8000/healthcheck/"]
      interval: 10s
      timeout: 5s
      retries: 5